namespace Study.PaymentGateway.API.Controllers.v1.Payments
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Study.PaymentGateway.API.Controllers.Base;
    using Study.PaymentGateway.App.Services.Interfaces;
    using Study.PaymentGateway.Shared.DTO.Payments;

    [Route("api/payments")]
    [ApiController]
    public class PaymentsController : BaseController
    {
        private IPaymentAppService paymentAppService;

        public PaymentsController(IPaymentAppService paymentAppService)
        {
            this.paymentAppService = paymentAppService;
        }

        /// <summary>
        /// Process a Payment.
        /// </summary>
        /// <param name="paymentDto">PAYMENT Object</param>
        /// <returns>the new created PAYMENT/returns>
        /// <response code="201">HTTPResponse with the newly created Payment</response>
        /// <response code="400">HTTPResponse with the PaymentDTO indicating the errors</response>
        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public async Task<IActionResult> ProcessPayment(PaymentDTO paymentDto)
        {
            var result = await this.paymentAppService.ProcessPaymentAsync(paymentDto);

            var locationName = nameof(ProcessPayment);
            var responseObject = new
            {
                id = result.Response.MerchantId,
                paymentId = result.Response.Id
            };

            return ProcessResponse(locationName, responseObject, result);
        }

        /// <summary>
        /// Gets A Payment by paymentID  generated by its processment
        /// </summary>
        /// <param name="id">Payment's ID</param>
        /// <returns>Returns a Payment when its found</returns>
        /// <response code="200">HTTPResponse with the found Payment</response>
        /// <response code="400">HTTPResponse with the PaymentDTO indicating the errors</response>
        [HttpGet("{id}")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public async Task<IActionResult> GetById(Guid id)
        {
            var result = await this.paymentAppService.GetByIdAsync(id);

            return ProcessResponse(result);
        }

        /// <summary>
        ///  Gets all the Payments made by a card
        /// </summary>
        /// <param name="cardNumber"> Last 4 Card Digits</param>
        /// <param name="currentPage"> Current page from pagination</param>
        /// <param name="itemsPerPage"> Total items per page</param>
        /// <returns> A paged result presenting all the Payments.</returns>
        /// <response code="204">HTTPResponse with PagedResult containing the found Payments</response>
        /// <response code="400">HTTPResponse with PagedResult containing the PaymentDTO indicating the errors</response>
        [HttpGet("")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public async Task<IActionResult> GetPaymentsByCardNumberPaged(int cardNumber, int currentPage, int itemsPerPage)
        {
            var result = await this.paymentAppService.GetPaymentByCardNumberAsync(cardNumber, currentPage, itemsPerPage);

            return ProcessResponse(result);
        }
    }
}