version: '3.4'

services:

  study.paymentgateway.zookeeper:
    container_name: study.paymentgateway.zookeeper
    ports:
        - 2181:2181
  
  study.paymentgateway.kafka:
    container_name:  study.paymentgateway.kafka
    ports:
        - 9092:9092
    environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_DELETE_TOPIC_ENABLE: 'true'
        KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
        KAFKA_MESSAGE_MAX_BYTES: 20971520
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - zookeeper

  study.paymentgateway.db:
    container_name:  study.paymentgateway.db
    volumes:
      - ${APPDATA}/site:/data/db
    ports:
      - "27017:27017"

  study.paymentgateway.api:
    container_name: study.paymanetgateway.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDBSettings:ConnectionString=mongodb://study.paymentgateway.db:27017"
    depends_on:
      - study.paymentgateway.db
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https/
      
